### ISSUE TITLE
Vs Gallery Link 404

### ISSUE THREAD

**Issue by bruceburge** [NLog/NLogSnippetsVSIX#1]
https://marketplace.visualstudio.com/vsgallery/15d51643-704d-4a35-b263-60eb31e3485d

![image](https://user-images.githubusercontent.com/6773890/28284413-83fb28f4-6af6-11e7-870d-a99d73b6fd5e.png)

**Comment by 304NotModified** [comment]
it's gone indeed. Dunno what happend. Will try to get it back online
